language: java
jdk:
  - oraclejdk8


//Install dependencies
gradle assemble
//Avoid uploading the cache after every build because gradle
before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/


